import { createHash, randomBytes } from "node:crypto";

const base64url = (value) => value.toString("base64url");
export class SearchConsoleOAuth {
  constructor({ fetchImpl = fetch } = {}) { this.fetch = fetchImpl; this.pending = new Map(); }
  begin({ ownerId, clientId, clientSecret, redirectUri, siteUrl }) { if (!clientId || !clientSecret || !redirectUri || !siteUrl) throw new Error("OAuth client, redirect URI and Search Console property are required"); const state = base64url(randomBytes(24)); const verifier = base64url(randomBytes(48)); const challenge = base64url(createHash("sha256").update(verifier).digest()); this.pending.set(state, { ownerId, clientId, clientSecret, redirectUri, siteUrl, verifier, createdAt: Date.now() }); const params = new URLSearchParams({ client_id: clientId, redirect_uri: redirectUri, response_type: "code", scope: "https://www.googleapis.com/auth/webmasters.readonly", access_type: "offline", prompt: "consent", state, code_challenge: challenge, code_challenge_method: "S256" }); return `https://accounts.google.com/o/oauth2/v2/auth?${params}`; }
  async exchange({ state, code }) { const request = this.pending.get(state); this.pending.delete(state); if (!request || Date.now() - request.createdAt > 10 * 60_000) throw new Error("OAuth request expired or is invalid"); const response = await this.fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: request.clientId, client_secret: request.clientSecret, redirect_uri: request.redirectUri, grant_type: "authorization_code", code_verifier: request.verifier }), signal: AbortSignal.timeout(30_000) }); const tokens = await response.json(); if (!response.ok) throw new Error(`Google OAuth failed: ${tokens.error_description ?? tokens.error}`); return { ownerId: request.ownerId, config: { siteUrl: request.siteUrl, clientId: request.clientId, clientSecret: request.clientSecret, accessToken: tokens.access_token, refreshToken: tokens.refresh_token, expiresAt: Date.now() + Number(tokens.expires_in ?? 3600) * 1000, scope: tokens.scope } }; }
  async refresh(config) { if (!config.refreshToken) throw new Error("Search Console OAuth refresh token is missing"); const response = await this.fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: config.clientId, client_secret: config.clientSecret, refresh_token: config.refreshToken, grant_type: "refresh_token" }), signal: AbortSignal.timeout(30_000) }); const tokens = await response.json(); if (!response.ok) throw new Error(`Google token refresh failed: ${tokens.error_description ?? tokens.error}`); return { ...config, accessToken: tokens.access_token, expiresAt: Date.now() + Number(tokens.expires_in ?? 3600) * 1000 };
  }
}
