import { useEffect, useState } from "react";
import { api } from "../../services/api.js";

export function AskPage() {
  const [prompt, setPrompt] = useState(""); const [answer, setAnswer] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [capabilities, setCapabilities] = useState([]); const [planGoal, setPlanGoal] = useState(""); const [capability, setCapability] = useState(""); const [planResult, setPlanResult] = useState(null);
  useEffect(() => { api.state().then((state) => { const available = (state.capabilities ?? []).filter((item) => item.providers?.length); setCapabilities(available); setCapability(available[0]?.id ?? ""); }).catch(() => {}); }, []);
  const ask = async (event) => { event.preventDefault(); if (!prompt.trim()) return; setBusy(true); setError(""); try { setAnswer(await api.aiChat({ prompt })); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const propose = async (event) => { event.preventDefault(); const selected = capabilities.find((item) => item.id === capability); if (!planGoal.trim() || !selected) return; setBusy(true); try { setPlanResult(await api.proposeAgentPlan({ goal: planGoal, nodes: [{ id: "step-1", pluginId: selected.providers[0].pluginId, capability: selected.id, description: planGoal }] })); setError(""); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  return <div className="stack"><form className="card" onSubmit={ask}><textarea rows="5" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Ask about SEO, pricing, content, leads, or your company operations" aria-label="Ask BusinessOS" /><div className="toolbar"><span className="muted">Grounded in your profile, catalog, and Company Brain.</span><button className="btn btn-primary" disabled={busy}>{busy ? "Thinking…" : "Ask BusinessOS"}</button></div></form>{error && <p className="auth-error" role="alert">{error}</p>}{answer && <article className="card"><h2>Answer</h2><p className="answer-text">{answer.text}</p><small className="muted">{answer.provider} · {answer.model}</small></article>}<form className="card" onSubmit={propose}><h2>Prepare a bounded plan</h2><p className="muted">Plans are proposals only. BusinessOS validates the capability and waits for your approval before any adapter can act.</p><div className="form-grid"><input value={planGoal} onChange={(event) => setPlanGoal(event.target.value)} placeholder="What outcome should be prepared?" aria-label="Plan goal" required /><select value={capability} onChange={(event) => setCapability(event.target.value)} aria-label="Registered capability">{capabilities.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select><button className="btn" disabled={busy || !capabilities.length}>Propose plan</button></div>{planResult && <div className="notice" aria-live="polite">Plan proposed and added to Needs You. Digest: {planResult.plan.digest.slice(0, 12)}…</div>}</form></div>;
}
